### ISSUE TITLE
mark authentication methods cram-md5, digest-md5, and login as deprecated

### ISSUE THREAD

**Issue by schengawegga** [pear/Auth_SASL#11]
mark authentication methods cram-md5, digest-md5, plain, login and anonymous as deprecated

**Comment by Neustradamus** [comment]
@schengawegga: PLAIN must not be noted "DEPRECATED".

**Comment by Neustradamus** [comment]
@schengawegga, @CloCkWeRX: Can you do it before the 1.2.0 build?

It is needed for https://github.com/pear/Net_SMTP.

**Comment by schengawegga** [comment]
@Neustradamus i will do that with the 1.1.1 build, these days.

**Comment by schengawegga** [comment]
@Neustradamus I don´t think, that we should mark "anonymous" as deprecated, because this method allows access to services that do not require authentication. The reason why these services do not require an authentication is not our problem. But if we deprecate this method now, we will remove it from this class, on the long run. And then this services can no longer be used. So i think, we should leave "anonymous" untouched.

**Comment by Neustradamus** [comment]
@schengawegga: Good catch, yes for anonymous, I have not seen the title before your change ^^

**Comment by Neustradamus** [comment]
@schengawegga: Good job!
- https://github.com/pear/Auth_SASL/issues/8
- https://github.com/pear/Auth_SASL/pull/14
- https://github.com/pear/Auth_SASL/releases/tag/v1.2.0

You can add the hashtag 11 too in 1.2.0 description :)
