### ISSUE TITLE
release version 1.2.0

### ISSUE THREAD

**Issue by schengawegga** [pear/Auth_SASL#8]
prepare and release version 1.2.0

**Comment by Neustradamus** [comment]
@schengawegga, @CloCkWeRX: Can you merge all from https://github.com/pear/Auth_SASL/tree/v1.2.0 into master and remove v1.2.0 branch?

Can you do this issue too?
- https://github.com/pear/Auth_SASL/issues/11

Can you create the build too?

**Comment by schengawegga** [comment]
@Neustradamus i will do an v1.1.1 build these days with the srcamsha224 bugfix.

**Comment by Neustradamus** [comment]
@schengawegga: Why not better to release the 1.2.0 with deprecated too?
It works with PHP 8.2 like Auth_SASL2?

**Comment by schengawegga** [comment]
@Neustradamus we will see. my time is very limited at the moment. so we will see what i can do in the next release.

**Comment by Neustradamus** [comment]
@schengawegga: Can you look to do before 2023 ending?

**Comment by schengawegga** [comment]
version 1.2.0 released

**Comment by Neustradamus** [comment]
@schengawegga: Good job!
- https://github.com/pear/Auth_SASL/releases/tag/v1.2.0
